import type { PageDefinition } from '../i18n/types';

/**
 * The page registry is the single source of truth for which pages exist.
 * Only `status: 'active'` entries are built, sitemapped, linked internally,
 * and eligible for hreflang. Draft/planned entries are never generated —
 * they document what's coming without publishing empty pages.
 */
export const pageRegistry: PageDefinition[] = [
  // ── en-US ────────────────────────────────────────────────────────────
  {
    id: 'en-us-home',
    locale: 'en-US',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'us salary and tax calculators',
    secondaryKeywords: ['paycheck calculator', 'take home pay calculator'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'en-us-salary-category',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'salary calculators',
    secondaryKeywords: ['paycheck calculator', 'hourly to salary'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'en-us-rent-category',
    locale: 'en-US',
    category: 'rent',
    slug: 'rent',
    pageType: 'category',
    primaryKeyword: 'rent calculators',
    secondaryKeywords: ['rent affordability', 'how much rent can i afford'],
    year: null,
    contentKey: 'rentCategory',
    status: 'active',
  },
  {
    id: 'en-us-salary-paycheck',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'paycheck calculator',
    secondaryKeywords: ['take home pay calculator', 'net pay calculator 2026', 'paycheck tax calculator'],
    year: 2026,
    contentKey: 'usPaycheck',
    equivalentPageGroup: 'paycheck-calculator',
    status: 'active',
  },
  {
    id: 'en-us-salary-to-hourly',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/salary-to-hourly',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'salary to hourly calculator',
    secondaryKeywords: ['annual to hourly wage', 'convert salary to hourly'],
    year: null,
    contentKey: 'salaryToHourly',
    equivalentPageGroup: 'salary-to-hourly',
    status: 'active',
  },
  {
    id: 'en-us-hourly-to-salary',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/hourly-to-salary',
    pageType: 'calculator',
    calculatorType: 'hourlyToSalary',
    primaryKeyword: 'hourly to salary calculator',
    secondaryKeywords: ['hourly wage to annual salary', 'hourly wage calculator'],
    year: null,
    contentKey: 'hourlyToSalary',
    equivalentPageGroup: 'hourly-to-salary',
    status: 'active',
  },
  {
    id: 'en-us-pay-frequency',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/pay-frequency-converter',
    pageType: 'calculator',
    calculatorType: 'payFrequencyConverter',
    primaryKeyword: 'pay frequency converter',
    secondaryKeywords: ['convert pay periods', 'monthly to biweekly pay'],
    year: null,
    contentKey: 'payFrequencyConverter',
    equivalentPageGroup: 'pay-frequency',
    status: 'active',
  },
  {
    id: 'en-us-salary-raise',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/salary-raise',
    pageType: 'calculator',
    calculatorType: 'salaryRaise',
    primaryKeyword: 'salary raise calculator',
    secondaryKeywords: ['pay increase calculator', 'percentage raise calculator'],
    year: null,
    contentKey: 'salaryRaise',
    equivalentPageGroup: 'salary-raise',
    status: 'active',
  },
  {
    id: 'en-us-rent-affordability',
    locale: 'en-US',
    category: 'rent',
    slug: 'rent/rent-affordability',
    pageType: 'calculator',
    calculatorType: 'rentAffordability',
    primaryKeyword: 'rent affordability calculator',
    secondaryKeywords: ['how much rent can i afford', '30 percent rule rent'],
    year: null,
    contentKey: 'rentAffordability',
    equivalentPageGroup: 'rent-affordability',
    status: 'active',
  },
  {
    id: 'en-us-states-category',
    locale: 'en-US',
    category: 'states',
    slug: 'states',
    pageType: 'category',
    primaryKeyword: 'us state paycheck calculators',
    secondaryKeywords: ['state paycheck calculator 2026', 'take home pay by state'],
    year: 2026,
    contentKey: 'stateCategory',
    status: 'active',
  },
  // US state pages
  {
    id: 'en-us-paycheck-florida',
    locale: 'en-US',
    category: 'states',
    slug: 'states/florida-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'florida paycheck calculator',
    secondaryKeywords: ['florida take home pay', 'paycheck calculator florida', 'florida salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckFL',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-texas',
    locale: 'en-US',
    category: 'states',
    slug: 'states/texas-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'texas paycheck calculator',
    secondaryKeywords: ['texas take home pay', 'paycheck calculator texas', 'texas salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckTX',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-new-york',
    locale: 'en-US',
    category: 'states',
    slug: 'states/new-york-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'new york paycheck calculator',
    secondaryKeywords: ['new york take home pay', 'ny paycheck calculator', 'new york salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckNY',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-arizona',
    locale: 'en-US',
    category: 'states',
    slug: 'states/arizona-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'arizona paycheck calculator',
    secondaryKeywords: ['arizona take home pay', 'paycheck calculator arizona', 'arizona salary 2026'],
    year: 2026,
    contentKey: 'usPaycheckAZ',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-annual-salary-calculator',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/annual-salary-calculator',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'annual salary calculator',
    secondaryKeywords: ['salary calculator', 'annual salary to hourly'],
    year: null,
    contentKey: 'annualSalaryCalculator',
    status: 'active',
  },
  {
    id: 'en-us-paystub-calculator',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/paystub-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'paystub calculator',
    secondaryKeywords: ['paycheck tax calculator', 'paycheck calculator'],
    year: 2026,
    contentKey: 'paystubCalculator',
    status: 'active',
  },
  {
    id: 'en-us-paycheck-illinois',
    locale: 'en-US',
    category: 'states',
    slug: 'states/illinois-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'illinois paycheck calculator',
    secondaryKeywords: ['illinois take home pay', 'paycheck calculator illinois', 'illinois salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckIL',
    status: 'active',
  },
  // ── de-DE ────────────────────────────────────────────────────────────
  {
    id: 'de-de-home',
    locale: 'de-DE',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'gehaltsrechner deutschland 2026',
    secondaryKeywords: ['brutto netto rechner 2026', 'mindestlohn 2026'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'de-de-salary-category',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'gehaltsrechner',
    secondaryKeywords: ['lohnrechner', 'brutto netto rechner 2026'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'de-de-mindestlohn',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/mindestlohn-rechner',
    pageType: 'calculator',
    calculatorType: 'deMindestlohn',
    primaryKeyword: 'mindestlohn rechner 2026',
    secondaryKeywords: ['mindestlohn 2026', 'gesetzlicher mindestlohn', 'gehaltsrechner stundenlohn'],
    year: 2026,
    contentKey: 'deMindestlohn',
    equivalentPageGroup: 'minimum-wage-calculator',
    status: 'active',
  },
  {
    id: 'de-de-brutto-netto',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/brutto-netto-rechner',
    pageType: 'calculator',
    calculatorType: 'deBruttoNetto',
    primaryKeyword: 'brutto netto rechner 2026',
    secondaryKeywords: ['gehaltsrechner 2026', 'sozialversicherungsbeiträge 2026', 'lohnrechner'],
    year: 2026,
    contentKey: 'deBruttoNetto',
    equivalentPageGroup: 'de-brutto-netto-rechner',
    status: 'active',
  },
  {
    id: 'de-de-stundenlohn',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/stundenlohn-rechner',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'stundenlohn rechner',
    secondaryKeywords: ['gehaltsrechner stundenlohn', 'lohnrechner'],
    year: null,
    contentKey: 'deStundenlohn',
    status: 'active',
  },
  {
    id: 'de-de-teilzeit',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/gehaltsrechner-teilzeit',
    pageType: 'calculator',
    calculatorType: 'dePartTimeSalary',
    primaryKeyword: 'gehaltsrechner teilzeit',
    secondaryKeywords: ['teilzeit gehalt berechnen'],
    year: null,
    contentKey: 'dePartTimeSalary',
    status: 'active',
  },
  {
    id: 'de-de-minijob',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/minijob-rechner',
    pageType: 'calculator',
    calculatorType: 'deMinijob',
    primaryKeyword: 'minijob rechner',
    secondaryKeywords: ['minijob grenze 2026'],
    year: 2026,
    contentKey: 'deMinijob',
    status: 'active',
  },
  {
    id: 'de-de-bayern',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/brutto-netto-rechner-bayern',
    pageType: 'calculator',
    calculatorType: 'deBruttoNetto',
    primaryKeyword: 'brutto netto rechner bayern',
    secondaryKeywords: ['gehalt bayern 2026'],
    year: 2026,
    contentKey: 'deBruttoNettoBayern',
    equivalentPageGroup: 'de-brutto-netto-rechner-bayern',
    status: 'active',
  },
  {
    id: 'de-de-nrw',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/brutto-netto-rechner-nrw',
    pageType: 'calculator',
    calculatorType: 'deBruttoNetto',
    primaryKeyword: 'brutto netto rechner nrw',
    secondaryKeywords: ['gehalt nrw 2026'],
    year: 2026,
    contentKey: 'deBruttoNettoNRW',
    equivalentPageGroup: 'de-brutto-netto-rechner-nrw',
    status: 'active',
  },
  { id:'de-de-tvoed-planned', locale:'de-DE', category:'salary', slug:'salary/gehaltsrechner-tvoed', pageType:'calculator', primaryKeyword:'gehaltsrechner tvöd', secondaryKeywords:['öffentlicher dienst gehalt'], year:2026, contentKey:'deTvoedPlanned', status:'planned' },
  { id:'de-de-oeffentlicher-dienst-planned', locale:'de-DE', category:'salary', slug:'salary/gehaltsrechner-oeffentlicher-dienst', pageType:'calculator', primaryKeyword:'gehaltsrechner öffentlicher dienst', secondaryKeywords:['tvöd gehaltsrechner'], year:2026, contentKey:'deOeffentlicherDienstPlanned', status:'planned' },
  // ── es-ES ────────────────────────────────────────────────────────────
  {
    id: 'es-es-home',
    locale: 'es-ES',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'calculadora de sueldo neto españa',
    secondaryKeywords: ['calculadora irpf 2026', 'calculadora nómina'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'es-es-salary-category',
    locale: 'es-ES',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'calculadoras de salario españa',
    secondaryKeywords: ['calculadora nómina', 'calculadora irpf'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'es-es-nomina',
    locale: 'es-ES',
    category: 'salary',
    slug: 'salary/calculadora-nomina',
    pageType: 'calculator',
    calculatorType: 'esNomina',
    primaryKeyword: 'calculadora de nómina irpf 2026',
    secondaryKeywords: ['calculadora irpf 2026', 'sueldo neto españa', 'calculadora seguridad social'],
    year: 2026,
    contentKey: 'esNomina',
    equivalentPageGroup: 'net-salary-calculator-es',
    status: 'active',
  },
  {
    id: 'es-es-labor-category',
    locale: 'es-ES',
    category: 'labor',
    slug: 'labor',
    pageType: 'category',
    primaryKeyword: 'calculadoras laborales españa',
    secondaryKeywords: ['calcular finiquito', 'indemnizacion despido'],
    year: null,
    contentKey: 'laborCategory',
    status: 'active',
  },
  {
    id: 'es-es-finiquito',
    locale: 'es-ES',
    category: 'labor',
    slug: 'labor/calcular-finiquito',
    pageType: 'calculator',
    calculatorType: 'esFiniquito',
    primaryKeyword: 'calcular finiquito',
    secondaryKeywords: ['calculo indemnizacion despido', 'finiquito baja voluntaria', 'indemnizacion por despido'],
    year: 2026,
    contentKey: 'esFiniquito',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'es-es-despido-improcedente',
    locale: 'es-ES',
    category: 'labor',
    slug: 'labor/calculadora-despido-improcedente',
    pageType: 'calculator',
    calculatorType: 'esFiniquito',
    primaryKeyword: 'calculadora despido improcedente',
    secondaryKeywords: ['calculo indemnizacion despido', 'indemnizacion por despido'],
    year: 2026,
    contentKey: 'esDespidoImprocedente',
    status: 'active',
  },
  // ── es-MX ────────────────────────────────────────────────────────────
  {
    id: 'es-mx-home',
    locale: 'es-MX',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'calculadora de isr y sueldo neto méxico',
    secondaryKeywords: ['calculadora isr 2026', 'sueldo neto méxico'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'es-mx-salary-category',
    locale: 'es-MX',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'calculadoras de sueldo méxico',
    secondaryKeywords: ['calculadora isr', 'sueldo neto'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'es-mx-isr',
    locale: 'es-MX',
    category: 'salary',
    slug: 'salary/calculadora-isr',
    pageType: 'calculator',
    calculatorType: 'mxIsr',
    primaryKeyword: 'calculadora isr 2026',
    secondaryKeywords: ['calculadora de isr', 'tarifa isr sat', 'sueldo bruto y neto', 'calculadora sueldo neto méxico', 'sueldo neto mexico'],
    year: 2026,
    contentKey: 'mxIsr',
    equivalentPageGroup: 'isr-calculator-mx',
    status: 'active',
  },
  {
    id: 'es-mx-labor-category',
    locale: 'es-MX',
    category: 'labor',
    slug: 'labor',
    pageType: 'category',
    primaryKeyword: 'calculadoras laborales méxico',
    secondaryKeywords: ['calculadora finiquito', 'liquidacion laboral'],
    year: null,
    contentKey: 'laborCategory',
    status: 'active',
  },
  {
    id: 'es-mx-finiquito',
    locale: 'es-MX',
    category: 'labor',
    slug: 'labor/calculadora-finiquito',
    pageType: 'calculator',
    calculatorType: 'mxFiniquito',
    primaryKeyword: 'calculadora de finiquito',
    secondaryKeywords: ['calculadora de liquidacion', 'finiquito mexico', 'liquidacion laboral'],
    year: 2026,
    contentKey: 'mxFiniquito',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'es-mx-liquidacion',
    locale: 'es-MX',
    category: 'labor',
    slug: 'labor/calculadora-liquidacion',
    pageType: 'calculator',
    calculatorType: 'mxFiniquito',
    primaryKeyword: 'calculadora de liquidacion',
    secondaryKeywords: ['liquidacion laboral', 'finiquito mexico'],
    year: 2026,
    contentKey: 'mxLiquidacion',
    status: 'active',
  },
  {
    id: 'es-mx-bruto-neto',
    locale: 'es-MX',
    category: 'salary',
    slug: 'salary/sueldo-bruto-y-neto',
    pageType: 'calculator',
    calculatorType: 'mxIsr',
    primaryKeyword: 'sueldo bruto y neto',
    secondaryKeywords: ['sueldo neto mexico', 'calculadora sueldo neto mexico'],
    year: 2026,
    contentKey: 'mxBrutoNeto',
    status: 'active',
  },
  // ── en-GB ────────────────────────────────────────────────────────────
  {
    id: 'en-gb-home',
    locale: 'en-GB',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'uk salary and tax calculators',
    secondaryKeywords: ['take home pay calculator uk', 'income tax calculator uk'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'en-gb-salary-category',
    locale: 'en-GB',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'uk salary calculators',
    secondaryKeywords: ['salary to hourly uk', 'take home pay calculator'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'en-gb-paycheck',
    locale: 'en-GB',
    category: 'salary',
    slug: 'salary/take-home-pay-calculator',
    pageType: 'calculator',
    calculatorType: 'gbPaycheck',
    primaryKeyword: 'take home pay calculator uk',
    secondaryKeywords: ['uk salary calculator 2026', 'income tax calculator uk', 'ni calculator uk', 'salary after tax uk'],
    year: 2026,
    contentKey: 'gbPaycheck',
    equivalentPageGroup: 'paycheck-calculator',
    status: 'active',
  },
  {
    id: 'en-gb-salary-to-hourly',
    locale: 'en-GB',
    category: 'salary',
    slug: 'salary/salary-to-hourly',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'salary to hourly calculator uk',
    secondaryKeywords: ['hourly rate calculator uk', 'hourly wage calculator', 'annual to hourly uk'],
    year: null,
    contentKey: 'salaryToHourly',
    equivalentPageGroup: 'salary-to-hourly',
    status: 'active',
  },
  // ── en-IE ────────────────────────────────────────────────────────────
  {
    id: 'en-ie-home',
    locale: 'en-IE',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'irish tax calculator',
    secondaryKeywords: ['take home pay calculator ireland', 'income tax calculator ireland'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'en-ie-salary-category',
    locale: 'en-IE',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'ireland salary calculators',
    secondaryKeywords: ['take home pay ireland', 'irish income tax'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'en-ie-paycheck',
    locale: 'en-IE',
    category: 'salary',
    slug: 'salary/take-home-pay-calculator',
    pageType: 'calculator',
    calculatorType: 'iePaycheck',
    primaryKeyword: 'take home pay calculator ireland',
    secondaryKeywords: ['tax calculator ireland', 'income tax calculator ireland', 'irish tax calculator 2026', 'usc calculator ireland'],
    year: 2026,
    contentKey: 'iePaycheck',
    equivalentPageGroup: 'paycheck-calculator',
    status: 'active',
  },
  // ── pt-BR ────────────────────────────────────────────────────────────
  {
    id: 'pt-br-home',
    locale: 'pt-BR',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'calculadora de salário brasil',
    secondaryKeywords: ['salário mínimo 2026', 'simulador salário líquido'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'pt-br-salary-category',
    locale: 'pt-BR',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'calculadoras de salário brasil',
    secondaryKeywords: ['calculadora rescisão', 'calcular décimo terceiro'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'pt-br-labor-category',
    locale: 'pt-BR',
    category: 'labor',
    slug: 'labor',
    pageType: 'category',
    primaryKeyword: 'calculadoras trabalhistas brasil',
    secondaryKeywords: ['calcular rescisão', 'calcular décimo terceiro'],
    year: null,
    contentKey: 'laborCategory',
    status: 'active',
  },
  {
    id: 'pt-br-rescisao',
    locale: 'pt-BR',
    category: 'labor',
    slug: 'labor/calcular-rescisao',
    pageType: 'calculator',
    calculatorType: 'brRescisao',
    primaryKeyword: 'calcular rescisão',
    secondaryKeywords: ['calculadora rescisão', 'calculo rescisao', 'rescisão trabalhista 2026'],
    year: 2026,
    contentKey: 'brRescisao',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'pt-br-decimo-terceiro',
    locale: 'pt-BR',
    category: 'labor',
    slug: 'labor/calcular-decimo-terceiro',
    pageType: 'calculator',
    calculatorType: 'brDecimoTerceiro',
    primaryKeyword: 'calcular décimo terceiro',
    secondaryKeywords: ['decimo terceiro salário', '13 salário', 'cálculo 13° salário 2026'],
    year: 2026,
    contentKey: 'brDecimoTerceiro',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'pt-br-salario-liquido',
    locale: 'pt-BR',
    category: 'salary',
    slug: 'salary/calculadora-salario-liquido',
    pageType: 'calculator',
    calculatorType: 'brSalarioLiquido',
    primaryKeyword: 'calculadora de salário líquido',
    secondaryKeywords: ['calcular salario liquido', 'salário bruto para líquido', 'salário líquido clt', 'simulador salário líquido 2026'],
    year: 2026,
    contentKey: 'brSalarioLiquido',
    status: 'active',
  },
  {
    id: 'pt-br-ferias',
    locale: 'pt-BR',
    category: 'labor',
    slug: 'labor/calcular-ferias',
    pageType: 'calculator',
    calculatorType: 'brFerias',
    primaryKeyword: 'calculadora de férias',
    secondaryKeywords: ['como calcular ferias', 'cálculo de férias', 'calculo de ferias proporcionais'],
    year: 2026,
    contentKey: 'brFerias',
    status: 'active',
  },
  {
    id: 'pt-br-horas-extras',
    locale: 'pt-BR',
    category: 'labor',
    slug: 'labor/calculadora-horas-extras',
    pageType: 'calculator',
    calculatorType: 'brHorasExtras',
    primaryKeyword: 'calculadora de horas extras',
    secondaryKeywords: ['horas extras cálculo'],
    year: 2026,
    contentKey: 'brHorasExtras',
    status: 'active',
  },
  // ── nl-NL ────────────────────────────────────────────────────────────
  {
    id: 'nl-nl-home',
    locale: 'nl-NL',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'netto salaris berekenen nederland',
    secondaryKeywords: ['bruto netto calculator', 'loonbelasting calculator'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'nl-nl-salary-category',
    locale: 'nl-NL',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'salaris calculators nederland',
    secondaryKeywords: ['bruto netto calculator', 'loon berekenen'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'nl-nl-bruto-netto',
    locale: 'nl-NL',
    category: 'salary',
    slug: 'salary/bruto-netto-calculator',
    pageType: 'calculator',
    calculatorType: 'nlBruttoNetto',
    primaryKeyword: 'bruto netto calculator',
    secondaryKeywords: ['netto salaris berekenen', 'loonbelasting 2026', 'salaris calculator nederland 2026'],
    year: 2026,
    contentKey: 'nlBruttoNetto',
    equivalentPageGroup: 'nl-bruto-netto-calculator',
    status: 'active',
  },
];

export function getActivePages(): PageDefinition[] {
  return pageRegistry.filter((p) => p.status === 'active');
}

export function getActivePagesForLocale(locale: string): PageDefinition[] {
  return getActivePages().filter((p) => p.locale === locale);
}

export function findActivePage(locale: string, slug: string): PageDefinition | undefined {
  return getActivePages().find((p) => p.locale === locale && p.slug === slug);
}

/** Pages sharing an equivalentPageGroup are true cross-locale equivalents, eligible for hreflang. */
export function findEquivalentPages(group: string): PageDefinition[] {
  return getActivePages().filter((p) => p.equivalentPageGroup === group);
}

/** Active pages that should appear in the sitemap (indexable defaults to true when unset). */
export function getIndexablePages(): PageDefinition[] {
  return getActivePages().filter((p) => p.indexable !== false);
}
