import type { PageDefinition } from '../i18n/types';

/**
 * The page registry is the single source of truth for which pages exist.
 * Only `status: 'active'` entries are built, sitemapped, linked internally,
 * and eligible for hreflang. Draft/planned entries are never generated —
 * they document what's coming without publishing empty pages.
 */
export const pageRegistry: PageDefinition[] = [
  // ── en-US ────────────────────────────────────────────────────────────
  {
    id: 'en-us-home',
    locale: 'en-US',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'us salary and tax calculators',
    secondaryKeywords: ['paycheck calculator', 'take home pay calculator'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'en-us-salary-category',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'salary calculators',
    secondaryKeywords: ['paycheck calculator', 'hourly to salary'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'en-us-rent-category',
    locale: 'en-US',
    category: 'rent',
    slug: 'rent',
    pageType: 'category',
    primaryKeyword: 'rent calculators',
    secondaryKeywords: ['rent affordability', 'how much rent can i afford'],
    year: null,
    contentKey: 'rentCategory',
    status: 'active',
  },
  {
    id: 'en-us-salary-paycheck',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'paycheck calculator',
    description: 'Estimate your take-home pay after federal income tax, Social Security, Medicare, and pre-tax deductions.',
    secondaryKeywords: ['take home pay calculator', 'net pay calculator 2026', 'paycheck tax calculator'],
    year: 2026,
    contentKey: 'usPaycheck',
    equivalentPageGroup: 'paycheck-calculator',
    status: 'active',
  },
  {
    id: 'en-us-salary-to-hourly',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/salary-to-hourly',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'salary to hourly calculator',
    description: 'See what your annual salary works out to as an hourly rate, based on your work schedule.',
    secondaryKeywords: ['annual to hourly wage', 'convert salary to hourly'],
    year: null,
    contentKey: 'salaryToHourly',
    equivalentPageGroup: 'salary-to-hourly',
    status: 'active',
  },
  {
    id: 'en-us-hourly-to-salary',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/hourly-to-salary',
    pageType: 'calculator',
    calculatorType: 'hourlyToSalary',
    primaryKeyword: 'hourly to salary calculator',
    description: 'Convert an hourly wage into an estimated annual salary based on your usual schedule.',
    secondaryKeywords: ['hourly wage to annual salary', 'hourly wage calculator'],
    year: null,
    contentKey: 'hourlyToSalary',
    equivalentPageGroup: 'hourly-to-salary',
    status: 'active',
  },
  {
    id: 'en-us-pay-frequency',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/pay-frequency-converter',
    pageType: 'calculator',
    calculatorType: 'payFrequencyConverter',
    primaryKeyword: 'pay frequency converter',
    description: 'Compare the same income across weekly, biweekly, semi-monthly, monthly, and annual pay.',
    secondaryKeywords: ['convert pay periods', 'monthly to biweekly pay'],
    year: null,
    contentKey: 'payFrequencyConverter',
    equivalentPageGroup: 'pay-frequency',
    status: 'active',
  },
  {
    id: 'en-us-salary-raise',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/salary-raise',
    pageType: 'calculator',
    calculatorType: 'salaryRaise',
    primaryKeyword: 'salary raise calculator',
    description: 'See how a percentage or fixed-dollar raise changes your salary and hourly rate.',
    secondaryKeywords: ['pay increase calculator', 'percentage raise calculator'],
    year: null,
    contentKey: 'salaryRaise',
    equivalentPageGroup: 'salary-raise',
    status: 'active',
  },
  {
    id: 'en-us-salary-raise-simulator',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/raise-simulator',
    pageType: 'calculator',
    calculatorType: 'usRaiseSimulator',
    primaryKeyword: 'salary raise simulator',
    description: 'Compare your current vs. raised salary with detailed tax breakdown showing exactly how much of your raise you keep after taxes.',
    secondaryKeywords: ['raise calculator with taxes', 'salary increase tax impact', 'paycheck raise simulator 2026'],
    year: 2026,
    contentKey: 'usRaiseSimulator',
    equivalentPageGroup: 'salary-raise-simulator',
    // No src/pages file exists for this slug yet, so 'active' was producing
    // a dead link everywhere this registry is used to render navigation.
    status: 'planned',
  },
  {
    id: 'en-us-salary-year-comparison',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/year-comparison',
    pageType: 'calculator',
    calculatorType: 'usYearComparison',
    primaryKeyword: 'salary year over year comparison',
    description: 'Compare your salary across different tax years with inflation adjustment and tax burden analysis.',
    secondaryKeywords: ['salary comparison calculator', 'year over year salary analysis', 'tax impact comparison 2026'],
    year: 2026,
    contentKey: 'usYearComparison',
    equivalentPageGroup: 'salary-year-comparison',
    // No src/pages file exists for this slug yet, so 'active' was producing
    // a dead link everywhere this registry is used to render navigation.
    status: 'planned',
  },
  {
    id: 'en-us-rent-affordability',
    locale: 'en-US',
    category: 'rent',
    slug: 'rent/rent-affordability',
    pageType: 'calculator',
    calculatorType: 'rentAffordability',
    primaryKeyword: 'rent affordability calculator',
    description: 'Estimate a starting rent budget from your income and the share you want to spend on housing.',
    secondaryKeywords: ['how much rent can i afford', '30 percent rule rent'],
    year: null,
    contentKey: 'rentAffordability',
    equivalentPageGroup: 'rent-affordability',
    status: 'active',
  },
  {
    id: 'en-us-states-category',
    locale: 'en-US',
    category: 'states',
    slug: 'states',
    pageType: 'category',
    primaryKeyword: 'us state paycheck calculators',
    secondaryKeywords: ['state paycheck calculator 2026', 'take home pay by state'],
    year: 2026,
    contentKey: 'stateCategory',
    status: 'active',
  },
  // US state pages
  {
    id: 'en-us-paycheck-florida',
    locale: 'en-US',
    category: 'states',
    slug: 'states/florida-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'florida paycheck calculator',
    description: 'Estimate your Florida take-home pay. Florida has no state individual income tax.',
    secondaryKeywords: ['florida take home pay', 'paycheck calculator florida', 'florida salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckFL',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-texas',
    locale: 'en-US',
    category: 'states',
    slug: 'states/texas-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'texas paycheck calculator',
    description: 'Estimate your Texas take-home pay. Texas has no state individual income tax.',
    secondaryKeywords: ['texas take home pay', 'paycheck calculator texas', 'texas salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckTX',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-new-york',
    locale: 'en-US',
    category: 'states',
    slug: 'states/new-york-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'new york paycheck calculator',
    description: 'Estimate your New York take-home pay with federal deductions and state income tax. NYC local tax is not included.',
    secondaryKeywords: ['new york take home pay', 'ny paycheck calculator', 'new york salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckNY',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-arizona',
    locale: 'en-US',
    category: 'states',
    slug: 'states/arizona-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'arizona paycheck calculator',
    description: 'Estimate your Arizona take-home pay using the state\'s 2.5% flat income-tax rate.',
    secondaryKeywords: ['arizona take home pay', 'paycheck calculator arizona', 'arizona salary 2026'],
    year: 2026,
    contentKey: 'usPaycheckAZ',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-annual-salary-calculator',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/annual-salary-calculator',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'annual salary calculator',
    description: 'Convert hourly, daily, weekly, or monthly earnings into an estimated annual salary.',
    secondaryKeywords: ['salary calculator', 'annual salary to hourly'],
    year: null,
    contentKey: 'annualSalaryCalculator',
    status: 'active',
  },
  {
    id: 'en-us-paystub-calculator',
    locale: 'en-US',
    category: 'salary',
    slug: 'salary/paystub-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'paystub calculator',
    description: 'See how gross pay, taxes, deductions, and take-home pay fit together on a paystub.',
    secondaryKeywords: ['paycheck tax calculator', 'paycheck calculator'],
    year: 2026,
    contentKey: 'paystubCalculator',
    status: 'active',
  },
  {
    id: 'en-us-paycheck-illinois',
    locale: 'en-US',
    category: 'states',
    slug: 'states/illinois-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'illinois paycheck calculator',
    description: 'Estimate your Illinois take-home pay using the state\'s 4.95% flat income-tax rate.',
    secondaryKeywords: ['illinois take home pay', 'paycheck calculator illinois', 'illinois salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckIL',
    status: 'active',
  },
  {
    id: 'en-us-paycheck-california',
    locale: 'en-US',
    category: 'states',
    slug: 'states/california-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'california paycheck calculator',
    description: 'Estimate your California take-home pay with the state\'s progressive income tax (1% to 13.3%) plus federal taxes.',
    secondaryKeywords: ['california take home pay', 'paycheck calculator california', 'california salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckCA',
    equivalentPageGroup: undefined,
        status: 'active',
  },
  {
    id: 'en-us-paycheck-new-jersey',
    locale: 'en-US',
    category: 'states',
    slug: 'states/new-jersey-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'new jersey paycheck calculator',
    description: 'Estimate your New Jersey take-home pay with the state\'s progressive income tax (1.4% to 10.75%) plus federal taxes.',
    secondaryKeywords: ['new jersey take home pay', 'nj paycheck calculator', 'new jersey salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckNJ',
    equivalentPageGroup: undefined,
        status: 'active',
  },
  {
    id: 'en-us-paycheck-pennsylvania',
    locale: 'en-US',
    category: 'states',
    slug: 'states/pennsylvania-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'pennsylvania paycheck calculator',
    description: 'Estimate your Pennsylvania take-home pay with the state\'s flat 3.07% income tax plus federal taxes.',
    secondaryKeywords: ['pennsylvania take home pay', 'pa paycheck calculator', 'pennsylvania salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckPA',
    equivalentPageGroup: undefined,
        status: 'active',
  },
  {
    id: 'en-us-paycheck-washington',
    locale: 'en-US',
    category: 'states',
    slug: 'states/washington-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'washington paycheck calculator',
    description: 'Estimate your Washington take-home pay. Washington State has no individual income tax.',
    secondaryKeywords: ['washington take home pay', 'paycheck calculator washington', 'washington salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckWA',
    equivalentPageGroup: undefined,
        status: 'active',
  },
  {
    id: 'en-us-paycheck-alabama',
    locale: 'en-US',
    category: 'states',
    slug: 'states/alabama-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'alabama paycheck calculator',
    description: 'Estimate your Alabama take-home pay with the state’s graduated income tax of 2% to 5%.',
    secondaryKeywords: ['alabama take home pay', 'paycheck calculator alabama', 'alabama salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckAL',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-alaska',
    locale: 'en-US',
    category: 'states',
    slug: 'states/alaska-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'alaska paycheck calculator',
    description: 'Estimate your Alaska take-home pay. Alaska has no state individual income tax.',
    secondaryKeywords: ['alaska take home pay', 'paycheck calculator alaska', 'alaska salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckAK',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-arkansas',
    locale: 'en-US',
    category: 'states',
    slug: 'states/arkansas-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'arkansas paycheck calculator',
    description: 'Estimate your Arkansas take-home pay with the state’s two-bracket income tax of 2% to 3.9%.',
    secondaryKeywords: ['arkansas take home pay', 'paycheck calculator arkansas', 'arkansas salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckAR',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-colorado',
    locale: 'en-US',
    category: 'states',
    slug: 'states/colorado-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'colorado paycheck calculator',
    description: 'Estimate your Colorado take-home pay with the 4.4% flat state income tax.',
    secondaryKeywords: ['colorado take home pay', 'paycheck calculator colorado', 'colorado salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckCO',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-connecticut',
    locale: 'en-US',
    category: 'states',
    slug: 'states/connecticut-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'connecticut paycheck calculator',
    description: 'Estimate your Connecticut take-home pay with the state’s graduated income tax of 2% to 6.99%.',
    secondaryKeywords: ['connecticut take home pay', 'paycheck calculator connecticut', 'connecticut salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckCT',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-delaware',
    locale: 'en-US',
    category: 'states',
    slug: 'states/delaware-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'delaware paycheck calculator',
    description: 'Estimate your Delaware take-home pay with the state’s graduated income tax of 2.2% to 6.6%.',
    secondaryKeywords: ['delaware take home pay', 'paycheck calculator delaware', 'delaware salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckDE',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-georgia',
    locale: 'en-US',
    category: 'states',
    slug: 'states/georgia-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'georgia paycheck calculator',
    description: 'Estimate your Georgia take-home pay with the 5.19% flat state income tax.',
    secondaryKeywords: ['georgia take home pay', 'paycheck calculator georgia', 'georgia salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckGA',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-hawaii',
    locale: 'en-US',
    category: 'states',
    slug: 'states/hawaii-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'hawaii paycheck calculator',
    description: 'Estimate your Hawaii take-home pay with the state’s graduated income tax of 1.4% to 11% across 12 brackets.',
    secondaryKeywords: ['hawaii take home pay', 'paycheck calculator hawaii', 'hawaii salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckHI',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-idaho',
    locale: 'en-US',
    category: 'states',
    slug: 'states/idaho-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'idaho paycheck calculator',
    description: 'Estimate your Idaho take-home pay with the 5.3% flat state income tax.',
    secondaryKeywords: ['idaho take home pay', 'paycheck calculator idaho', 'idaho salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckID',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-indiana',
    locale: 'en-US',
    category: 'states',
    slug: 'states/indiana-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'indiana paycheck calculator',
    description: 'Estimate your Indiana take-home pay with the 2.95% flat state income tax.',
    secondaryKeywords: ['indiana take home pay', 'paycheck calculator indiana', 'indiana salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckIN',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-iowa',
    locale: 'en-US',
    category: 'states',
    slug: 'states/iowa-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'iowa paycheck calculator',
    description: 'Estimate your Iowa take-home pay with the 3.8% flat state income tax.',
    secondaryKeywords: ['iowa take home pay', 'paycheck calculator iowa', 'iowa salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckIA',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-kansas',
    locale: 'en-US',
    category: 'states',
    slug: 'states/kansas-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'kansas paycheck calculator',
    description: 'Estimate your Kansas take-home pay with the state’s two-bracket income tax of 5.2% to 5.58%.',
    secondaryKeywords: ['kansas take home pay', 'paycheck calculator kansas', 'kansas salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckKS',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-kentucky',
    locale: 'en-US',
    category: 'states',
    slug: 'states/kentucky-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'kentucky paycheck calculator',
    description: 'Estimate your Kentucky take-home pay with the 3.5% flat state income tax.',
    secondaryKeywords: ['kentucky take home pay', 'paycheck calculator kentucky', 'kentucky salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckKY',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-louisiana',
    locale: 'en-US',
    category: 'states',
    slug: 'states/louisiana-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'louisiana paycheck calculator',
    description: 'Estimate your Louisiana take-home pay with the 3% flat state income tax.',
    secondaryKeywords: ['louisiana take home pay', 'paycheck calculator louisiana', 'louisiana salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckLA',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-maine',
    locale: 'en-US',
    category: 'states',
    slug: 'states/maine-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'maine paycheck calculator',
    description: 'Estimate your Maine take-home pay with the state’s graduated income tax of 5.8% to 7.15%.',
    secondaryKeywords: ['maine take home pay', 'paycheck calculator maine', 'maine salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckME',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-maryland',
    locale: 'en-US',
    category: 'states',
    slug: 'states/maryland-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'maryland paycheck calculator',
    description: 'Estimate your Maryland take-home pay with the state’s graduated income tax of 2% to 6.5%.',
    secondaryKeywords: ['maryland take home pay', 'paycheck calculator maryland', 'maryland salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckMD',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-massachusetts',
    locale: 'en-US',
    category: 'states',
    slug: 'states/massachusetts-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'massachusetts paycheck calculator',
    description: 'Estimate your Massachusetts take-home pay with the state’s 5% flat tax plus a 4% surtax on income over $1,083,150.',
    secondaryKeywords: ['massachusetts take home pay', 'paycheck calculator massachusetts', 'massachusetts salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckMA',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-michigan',
    locale: 'en-US',
    category: 'states',
    slug: 'states/michigan-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'michigan paycheck calculator',
    description: 'Estimate your Michigan take-home pay with the 4.25% flat state income tax.',
    secondaryKeywords: ['michigan take home pay', 'paycheck calculator michigan', 'michigan salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckMI',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-minnesota',
    locale: 'en-US',
    category: 'states',
    slug: 'states/minnesota-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'minnesota paycheck calculator',
    description: 'Estimate your Minnesota take-home pay with the state’s graduated income tax of 5.35% to 9.85%.',
    secondaryKeywords: ['minnesota take home pay', 'paycheck calculator minnesota', 'minnesota salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckMN',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-mississippi',
    locale: 'en-US',
    category: 'states',
    slug: 'states/mississippi-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'mississippi paycheck calculator',
    description: 'Estimate your Mississippi take-home pay with the 4% flat state income tax.',
    secondaryKeywords: ['mississippi take home pay', 'paycheck calculator mississippi', 'mississippi salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckMS',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-missouri',
    locale: 'en-US',
    category: 'states',
    slug: 'states/missouri-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'missouri paycheck calculator',
    description: 'Estimate your Missouri take-home pay with the state’s graduated income tax of 2% to 4.7%.',
    secondaryKeywords: ['missouri take home pay', 'paycheck calculator missouri', 'missouri salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckMO',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-montana',
    locale: 'en-US',
    category: 'states',
    slug: 'states/montana-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'montana paycheck calculator',
    description: 'Estimate your Montana take-home pay with the state’s two-bracket income tax of 4.7% to 5.65%.',
    secondaryKeywords: ['montana take home pay', 'paycheck calculator montana', 'montana salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckMT',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-nebraska',
    locale: 'en-US',
    category: 'states',
    slug: 'states/nebraska-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'nebraska paycheck calculator',
    description: 'Estimate your Nebraska take-home pay with the state’s graduated income tax of 2.46% to 4.55%.',
    secondaryKeywords: ['nebraska take home pay', 'paycheck calculator nebraska', 'nebraska salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckNE',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-nevada',
    locale: 'en-US',
    category: 'states',
    slug: 'states/nevada-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'nevada paycheck calculator',
    description: 'Estimate your Nevada take-home pay. Nevada has no state individual income tax.',
    secondaryKeywords: ['nevada take home pay', 'paycheck calculator nevada', 'nevada salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckNV',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-new-hampshire',
    locale: 'en-US',
    category: 'states',
    slug: 'states/new-hampshire-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'new hampshire paycheck calculator',
    description: 'Estimate your New Hampshire take-home pay. New Hampshire has no state individual income tax.',
    secondaryKeywords: ['new hampshire take home pay', 'paycheck calculator new hampshire', 'new hampshire salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckNH',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-new-mexico',
    locale: 'en-US',
    category: 'states',
    slug: 'states/new-mexico-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'new mexico paycheck calculator',
    description: 'Estimate your New Mexico take-home pay with the state’s graduated income tax of 1.5% to 5.9%.',
    secondaryKeywords: ['new mexico take home pay', 'paycheck calculator new mexico', 'new mexico salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckNM',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-north-carolina',
    locale: 'en-US',
    category: 'states',
    slug: 'states/north-carolina-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'north carolina paycheck calculator',
    description: 'Estimate your North Carolina take-home pay with the 3.99% flat state income tax.',
    secondaryKeywords: ['north carolina take home pay', 'paycheck calculator north carolina', 'north carolina salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckNC',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-north-dakota',
    locale: 'en-US',
    category: 'states',
    slug: 'states/north-dakota-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'north dakota paycheck calculator',
    description: 'Estimate your North Dakota take-home pay with the state’s two-bracket income tax of 1.95% to 2.5%.',
    secondaryKeywords: ['north dakota take home pay', 'paycheck calculator north dakota', 'north dakota salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckND',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-ohio',
    locale: 'en-US',
    category: 'states',
    slug: 'states/ohio-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'ohio paycheck calculator',
    description: 'Estimate your Ohio take-home pay with the 2.75% flat state income tax.',
    secondaryKeywords: ['ohio take home pay', 'paycheck calculator ohio', 'ohio salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckOH',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-oklahoma',
    locale: 'en-US',
    category: 'states',
    slug: 'states/oklahoma-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'oklahoma paycheck calculator',
    description: 'Estimate your Oklahoma take-home pay with the state’s graduated income tax of 2.5% to 4.5%.',
    secondaryKeywords: ['oklahoma take home pay', 'paycheck calculator oklahoma', 'oklahoma salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckOK',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-oregon',
    locale: 'en-US',
    category: 'states',
    slug: 'states/oregon-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'oregon paycheck calculator',
    description: 'Estimate your Oregon take-home pay with the state’s graduated income tax of 4.75% to 9.9%.',
    secondaryKeywords: ['oregon take home pay', 'paycheck calculator oregon', 'oregon salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckOR',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-rhode-island',
    locale: 'en-US',
    category: 'states',
    slug: 'states/rhode-island-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'rhode island paycheck calculator',
    description: 'Estimate your Rhode Island take-home pay with the state’s graduated income tax of 3.75% to 5.99%.',
    secondaryKeywords: ['rhode island take home pay', 'paycheck calculator rhode island', 'rhode island salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckRI',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-south-carolina',
    locale: 'en-US',
    category: 'states',
    slug: 'states/south-carolina-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'south carolina paycheck calculator',
    description: 'Estimate your South Carolina take-home pay with the state’s graduated income tax of 3% to 6%.',
    secondaryKeywords: ['south carolina take home pay', 'paycheck calculator south carolina', 'south carolina salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckSC',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-south-dakota',
    locale: 'en-US',
    category: 'states',
    slug: 'states/south-dakota-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'south dakota paycheck calculator',
    description: 'Estimate your South Dakota take-home pay. South Dakota has no state individual income tax.',
    secondaryKeywords: ['south dakota take home pay', 'paycheck calculator south dakota', 'south dakota salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckSD',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-tennessee',
    locale: 'en-US',
    category: 'states',
    slug: 'states/tennessee-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'tennessee paycheck calculator',
    description: 'Estimate your Tennessee take-home pay. Tennessee has no state individual income tax.',
    secondaryKeywords: ['tennessee take home pay', 'paycheck calculator tennessee', 'tennessee salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckTN',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-utah',
    locale: 'en-US',
    category: 'states',
    slug: 'states/utah-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'utah paycheck calculator',
    description: 'Estimate your Utah take-home pay with the 4.5% flat state income tax.',
    secondaryKeywords: ['utah take home pay', 'paycheck calculator utah', 'utah salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckUT',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-vermont',
    locale: 'en-US',
    category: 'states',
    slug: 'states/vermont-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'vermont paycheck calculator',
    description: 'Estimate your Vermont take-home pay with the state’s graduated income tax of 3.35% to 8.75%.',
    secondaryKeywords: ['vermont take home pay', 'paycheck calculator vermont', 'vermont salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckVT',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-virginia',
    locale: 'en-US',
    category: 'states',
    slug: 'states/virginia-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'virginia paycheck calculator',
    description: 'Estimate your Virginia take-home pay with the state’s graduated income tax of 2% to 5.75%.',
    secondaryKeywords: ['virginia take home pay', 'paycheck calculator virginia', 'virginia salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckVA',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-west-virginia',
    locale: 'en-US',
    category: 'states',
    slug: 'states/west-virginia-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'west virginia paycheck calculator',
    description: 'Estimate your West Virginia take-home pay with the state’s graduated income tax of 2.11% to 4.58%.',
    secondaryKeywords: ['west virginia take home pay', 'paycheck calculator west virginia', 'west virginia salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckWV',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-wisconsin',
    locale: 'en-US',
    category: 'states',
    slug: 'states/wisconsin-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'wisconsin paycheck calculator',
    description: 'Estimate your Wisconsin take-home pay with the state’s graduated income tax of 3.5% to 7.65%.',
    secondaryKeywords: ['wisconsin take home pay', 'paycheck calculator wisconsin', 'wisconsin salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckWI',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'en-us-paycheck-wyoming',
    locale: 'en-US',
    category: 'states',
    slug: 'states/wyoming-paycheck-calculator',
    pageType: 'calculator',
    calculatorType: 'usPaycheck',
    primaryKeyword: 'wyoming paycheck calculator',
    description: 'Estimate your Wyoming take-home pay. Wyoming has no state individual income tax.',
    secondaryKeywords: ['wyoming take home pay', 'paycheck calculator wyoming', 'wyoming salary calculator 2026'],
    year: 2026,
    contentKey: 'usPaycheckWY',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  // ── de-DE ────────────────────────────────────────────────────────────
  {
    id: 'de-de-home',
    locale: 'de-DE',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'gehaltsrechner deutschland 2026',
    secondaryKeywords: ['brutto netto rechner 2026', 'mindestlohn 2026'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'de-de-salary-category',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'gehaltsrechner',
    secondaryKeywords: ['lohnrechner', 'brutto netto rechner 2026'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'de-de-mindestlohn',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/mindestlohn-rechner',
    pageType: 'calculator',
    calculatorType: 'deMindestlohn',
    primaryKeyword: 'mindestlohn rechner 2026',
    description: 'Berechnen Sie Ihren Wochen-, Monats- und Jahreslohn auf Basis des aktuellen Mindestlohns.',
    secondaryKeywords: ['mindestlohn 2026', 'gesetzlicher mindestlohn', 'gehaltsrechner stundenlohn'],
    year: 2026,
    contentKey: 'deMindestlohn',
    equivalentPageGroup: 'minimum-wage-calculator',
    status: 'active',
  },
  {
    id: 'de-de-brutto-netto',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/brutto-netto-rechner',
    pageType: 'calculator',
    calculatorType: 'deBruttoNetto',
    primaryKeyword: 'brutto netto rechner 2026',
    description: 'Berechnen Sie Ihr Nettogehalt nach Sozialversicherung und Steuern für 2026.',
    secondaryKeywords: ['gehaltsrechner 2026', 'sozialversicherungsbeiträge 2026', 'lohnrechner'],
    year: 2026,
    contentKey: 'deBruttoNetto',
    equivalentPageGroup: 'de-brutto-netto-rechner',
    status: 'active',
  },
  {
    id: 'de-de-stundenlohn',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/stundenlohn-rechner',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'stundenlohn rechner',
    description: 'Rechnen Sie Ihr Jahresgehalt in einen Stundenlohn um.',
    secondaryKeywords: ['gehaltsrechner stundenlohn', 'lohnrechner'],
    year: null,
    contentKey: 'deStundenlohn',
    status: 'active',
  },
  {
    id: 'de-de-teilzeit',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/gehaltsrechner-teilzeit',
    pageType: 'calculator',
    calculatorType: 'dePartTimeSalary',
    primaryKeyword: 'gehaltsrechner teilzeit',
    description: 'Berechnen Sie Ihr Gehalt bei reduzierter Arbeitszeit und Teilzeitmodellen.',
    secondaryKeywords: ['teilzeit gehalt berechnen'],
    year: null,
    contentKey: 'dePartTimeSalary',
    status: 'active',
  },
  {
    id: 'de-de-minijob',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/minijob-rechner',
    pageType: 'calculator',
    calculatorType: 'deMinijob',
    primaryKeyword: 'minijob rechner',
    description: 'Prüfen Sie die Minijob-Grenze und berechnen Sie Ihren Verdienst für 2026.',
    secondaryKeywords: ['minijob grenze 2026'],
    year: 2026,
    contentKey: 'deMinijob',
    status: 'active',
  },
  {
    id: 'de-de-bayern',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/brutto-netto-rechner-bayern',
    pageType: 'calculator',
    calculatorType: 'deBruttoNetto',
    primaryKeyword: 'brutto netto rechner bayern',
    description: 'Brutto-Netto-Rechner mit Kirchensteuer 8% für Bayern.',
    secondaryKeywords: ['gehalt bayern 2026'],
    year: 2026,
    contentKey: 'deBruttoNettoBayern',
    equivalentPageGroup: 'de-brutto-netto-rechner-bayern',
    status: 'active',
  },
  {
    id: 'de-de-nrw',
    locale: 'de-DE',
    category: 'salary',
    slug: 'salary/brutto-netto-rechner-nrw',
    pageType: 'calculator',
    calculatorType: 'deBruttoNetto',
    primaryKeyword: 'brutto netto rechner nrw',
    description: 'Brutto-Netto-Rechner mit Kirchensteuer 9% für Nordrhein-Westfalen.',
    secondaryKeywords: ['gehalt nrw 2026'],
    year: 2026,
    contentKey: 'deBruttoNettoNRW',
    equivalentPageGroup: 'de-brutto-netto-rechner-nrw',
    status: 'active',
  },
  { id:'de-de-tvoed-planned', locale:'de-DE', category:'salary', slug:'salary/gehaltsrechner-tvoed', pageType:'calculator', primaryKeyword:'gehaltsrechner tvöd', secondaryKeywords:['öffentlicher dienst gehalt'], year:2026, contentKey:'deTvoedPlanned', status:'planned' },
  { id:'de-de-oeffentlicher-dienst-planned', locale:'de-DE', category:'salary', slug:'salary/gehaltsrechner-oeffentlicher-dienst', pageType:'calculator', primaryKeyword:'gehaltsrechner öffentlicher dienst', secondaryKeywords:['tvöd gehaltsrechner'], year:2026, contentKey:'deOeffentlicherDienstPlanned', status:'planned' },
  // ── es-ES ────────────────────────────────────────────────────────────
  {
    id: 'es-es-home',
    locale: 'es-ES',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'calculadora de sueldo neto españa',
    secondaryKeywords: ['calculadora irpf 2026', 'calculadora nómina'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'es-es-salary-category',
    locale: 'es-ES',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'calculadoras de salario españa',
    secondaryKeywords: ['calculadora nómina', 'calculadora irpf'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'es-es-nomina',
    locale: 'es-ES',
    category: 'salary',
    slug: 'salary/calculadora-nomina',
    pageType: 'calculator',
    calculatorType: 'esNomina',
    primaryKeyword: 'calculadora de nómina irpf 2026',
    description: 'Calcula tu sueldo neto con retenciones IRPF y Seguridad Social para 2026.',
    secondaryKeywords: ['calculadora irpf 2026', 'sueldo neto españa', 'calculadora seguridad social'],
    year: 2026,
    contentKey: 'esNomina',
    equivalentPageGroup: 'net-salary-calculator-es',
    status: 'active',
  },
  {
    id: 'es-es-labor-category',
    locale: 'es-ES',
    category: 'labor',
    slug: 'labor',
    pageType: 'category',
    primaryKeyword: 'calculadoras laborales españa',
    secondaryKeywords: ['calcular finiquito', 'indemnizacion despido'],
    year: null,
    contentKey: 'laborCategory',
    status: 'active',
  },
  {
    id: 'es-es-finiquito',
    locale: 'es-ES',
    category: 'labor',
    slug: 'labor/calcular-finiquito',
    pageType: 'calculator',
    calculatorType: 'esFiniquito',
    primaryKeyword: 'calcular finiquito',
    description: 'Calcula tu finiquito incluyendo vacaciones, pagas extra e indemnización.',
    secondaryKeywords: ['calculo indemnizacion despido', 'finiquito baja voluntaria', 'indemnizacion por despido'],
    year: 2026,
    contentKey: 'esFiniquito',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'es-es-despido-improcedente',
    locale: 'es-ES',
    category: 'labor',
    slug: 'labor/calculadora-despido-improcedente',
    pageType: 'calculator',
    calculatorType: 'esFiniquito',
    primaryKeyword: 'calculadora despido improcedente',
    description: 'Calcula la indemnización por despido improcedente según el Estatuto de los Trabajadores.',
    secondaryKeywords: ['calculo indemnizacion despido', 'indemnizacion por despido'],
    year: 2026,
    contentKey: 'esDespidoImprocedente',
    status: 'active',
  },
  // ── es-MX ────────────────────────────────────────────────────────────
  {
    id: 'es-mx-home',
    locale: 'es-MX',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'calculadora de isr y sueldo neto méxico',
    secondaryKeywords: ['calculadora isr 2026', 'sueldo neto méxico'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'es-mx-salary-category',
    locale: 'es-MX',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'calculadoras de sueldo méxico',
    secondaryKeywords: ['calculadora isr', 'sueldo neto'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'es-mx-isr',
    locale: 'es-MX',
    category: 'salary',
    slug: 'salary/calculadora-isr',
    pageType: 'calculator',
    calculatorType: 'mxIsr',
    primaryKeyword: 'calculadora isr 2026',
    description: 'Calcula tu ISR mensual con la tarifa oficial del SAT y conoce tu sueldo neto.',
    secondaryKeywords: ['calculadora de isr', 'tarifa isr sat', 'sueldo bruto y neto', 'calculadora sueldo neto méxico', 'sueldo neto mexico'],
    year: 2026,
    contentKey: 'mxIsr',
    equivalentPageGroup: 'isr-calculator-mx',
    status: 'active',
  },
  {
    id: 'es-mx-labor-category',
    locale: 'es-MX',
    category: 'labor',
    slug: 'labor',
    pageType: 'category',
    primaryKeyword: 'calculadoras laborales méxico',
    secondaryKeywords: ['calculadora finiquito', 'liquidacion laboral'],
    year: null,
    contentKey: 'laborCategory',
    status: 'active',
  },
  {
    id: 'es-mx-finiquito',
    locale: 'es-MX',
    category: 'labor',
    slug: 'labor/calculadora-finiquito',
    pageType: 'calculator',
    calculatorType: 'mxFiniquito',
    primaryKeyword: 'calculadora de finiquito',
    description: 'Calcula tu finiquito conforme a la Ley Federal del Trabajo de México.',
    secondaryKeywords: ['calculadora de liquidacion', 'finiquito mexico', 'liquidacion laboral'],
    year: 2026,
    contentKey: 'mxFiniquito',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'es-mx-liquidacion',
    locale: 'es-MX',
    category: 'labor',
    slug: 'labor/calculadora-liquidacion',
    pageType: 'calculator',
    calculatorType: 'mxFiniquito',
    primaryKeyword: 'calculadora de liquidacion',
    description: 'Calcula tu liquidación laboral incluyendo indemnización, prima y prestaciones.',
    secondaryKeywords: ['liquidacion laboral', 'finiquito mexico'],
    year: 2026,
    contentKey: 'mxLiquidacion',
    status: 'active',
  },
  {
    id: 'es-mx-bruto-neto',
    locale: 'es-MX',
    category: 'salary',
    slug: 'salary/sueldo-bruto-y-neto',
    pageType: 'calculator',
    calculatorType: 'mxIsr',
    primaryKeyword: 'sueldo bruto y neto',
    description: 'Convierte tu sueldo bruto a neto con deducciones ISR e IMSS de México.',
    secondaryKeywords: ['sueldo neto mexico', 'calculadora sueldo neto mexico'],
    year: 2026,
    contentKey: 'mxBrutoNeto',
    status: 'active',
  },
  // ── en-GB ────────────────────────────────────────────────────────────
  {
    id: 'en-gb-home',
    locale: 'en-GB',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'uk salary and tax calculators',
    secondaryKeywords: ['take home pay calculator uk', 'income tax calculator uk'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'en-gb-salary-category',
    locale: 'en-GB',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'uk salary calculators',
    secondaryKeywords: ['salary to hourly uk', 'take home pay calculator'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'en-gb-paycheck',
    locale: 'en-GB',
    category: 'salary',
    slug: 'salary/take-home-pay-calculator',
    pageType: 'calculator',
    calculatorType: 'gbPaycheck',
    primaryKeyword: 'take home pay calculator uk',
    description: 'Calculate your UK take-home pay after income tax, NI, and pension for 2025–26.',
    secondaryKeywords: ['uk salary calculator 2026', 'income tax calculator uk', 'ni calculator uk', 'salary after tax uk'],
    year: 2026,
    contentKey: 'gbPaycheck',
    equivalentPageGroup: 'paycheck-calculator',
    status: 'active',
  },
  {
    id: 'en-gb-salary-to-hourly',
    locale: 'en-GB',
    category: 'salary',
    slug: 'salary/salary-to-hourly',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'salary to hourly calculator uk',
    description: 'Convert your UK annual salary to an hourly rate based on your working hours.',
    secondaryKeywords: ['hourly rate calculator uk', 'hourly wage calculator', 'annual to hourly uk'],
    year: null,
    contentKey: 'salaryToHourly',
    equivalentPageGroup: 'salary-to-hourly',
    status: 'active',
  },
  // ── en-IE ────────────────────────────────────────────────────────────
  {
    id: 'en-ie-home',
    locale: 'en-IE',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'irish tax calculator',
    secondaryKeywords: ['take home pay calculator ireland', 'income tax calculator ireland'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'en-ie-salary-category',
    locale: 'en-IE',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'ireland salary calculators',
    secondaryKeywords: ['take home pay ireland', 'irish income tax'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'en-ie-paycheck',
    locale: 'en-IE',
    category: 'salary',
    slug: 'salary/take-home-pay-calculator',
    pageType: 'calculator',
    calculatorType: 'iePaycheck',
    primaryKeyword: 'take home pay calculator ireland',
    description: 'Estimate your Irish net pay after PAYE, USC, and PRSI deductions for 2026.',
    secondaryKeywords: ['tax calculator ireland', 'income tax calculator ireland', 'irish tax calculator 2026', 'usc calculator ireland'],
    year: 2026,
    contentKey: 'iePaycheck',
    equivalentPageGroup: 'paycheck-calculator',
    status: 'active',
  },
  // ── pt-BR ────────────────────────────────────────────────────────────
  {
    id: 'pt-br-home',
    locale: 'pt-BR',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'calculadora de salário brasil',
    secondaryKeywords: ['salário mínimo 2026', 'simulador salário líquido'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'pt-br-salary-category',
    locale: 'pt-BR',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'calculadoras de salário brasil',
    secondaryKeywords: ['calculadora rescisão', 'calcular décimo terceiro'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'pt-br-labor-category',
    locale: 'pt-BR',
    category: 'labor',
    slug: 'labor',
    pageType: 'category',
    primaryKeyword: 'calculadoras trabalhistas brasil',
    secondaryKeywords: ['calcular rescisão', 'calcular décimo terceiro'],
    year: null,
    contentKey: 'laborCategory',
    status: 'active',
  },
  {
    id: 'pt-br-rescisao',
    locale: 'pt-BR',
    category: 'labor',
    slug: 'labor/calcular-rescisao',
    pageType: 'calculator',
    calculatorType: 'brRescisao',
    primaryKeyword: 'calcular rescisão',
    description: 'Calcule sua rescisão trabalhista com saldo de salário, férias, 13º e FGTS.',
    secondaryKeywords: ['calculadora rescisão', 'calculo rescisao', 'rescisão trabalhista 2026'],
    year: 2026,
    contentKey: 'brRescisao',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'pt-br-decimo-terceiro',
    locale: 'pt-BR',
    category: 'labor',
    slug: 'labor/calcular-decimo-terceiro',
    pageType: 'calculator',
    calculatorType: 'brDecimoTerceiro',
    primaryKeyword: 'calcular décimo terceiro',
    description: 'Calcule seu 13º salário proporcional ao tempo trabalhado no ano.',
    secondaryKeywords: ['decimo terceiro salário', '13 salário', 'cálculo 13° salário 2026'],
    year: 2026,
    contentKey: 'brDecimoTerceiro',
    equivalentPageGroup: undefined,
    status: 'active',
  },
  {
    id: 'pt-br-salario-liquido',
    locale: 'pt-BR',
    category: 'salary',
    slug: 'salary/calculadora-salario-liquido',
    pageType: 'calculator',
    calculatorType: 'brSalarioLiquido',
    primaryKeyword: 'calculadora de salário líquido',
    description: 'Descubra seu salário líquido CLT após INSS e IRRF para 2026.',
    secondaryKeywords: ['calcular salario liquido', 'salário bruto para líquido', 'salário líquido clt', 'simulador salário líquido 2026'],
    year: 2026,
    contentKey: 'brSalarioLiquido',
    status: 'active',
  },
  {
    id: 'pt-br-ferias',
    locale: 'pt-BR',
    category: 'labor',
    slug: 'labor/calcular-ferias',
    pageType: 'calculator',
    calculatorType: 'brFerias',
    primaryKeyword: 'calculadora de férias',
    description: 'Calcule o valor das suas férias incluindo o terço constitucional.',
    secondaryKeywords: ['como calcular ferias', 'cálculo de férias', 'calculo de ferias proporcionais'],
    year: 2026,
    contentKey: 'brFerias',
    status: 'active',
  },
  {
    id: 'pt-br-horas-extras',
    locale: 'pt-BR',
    category: 'labor',
    slug: 'labor/calculadora-horas-extras',
    pageType: 'calculator',
    calculatorType: 'brHorasExtras',
    primaryKeyword: 'calculadora de horas extras',
    description: 'Calcule o valor das suas horas extras com os adicionais da CLT.',
    secondaryKeywords: ['horas extras cálculo'],
    year: 2026,
    contentKey: 'brHorasExtras',
    status: 'active',
  },
  // ── nl-NL ────────────────────────────────────────────────────────────
  {
    id: 'nl-nl-home',
    locale: 'nl-NL',
    category: 'guides',
    slug: '',
    pageType: 'home',
    primaryKeyword: 'netto salaris berekenen nederland',
    secondaryKeywords: ['bruto netto calculator', 'loonbelasting calculator'],
    year: null,
    contentKey: 'localeHome',
    status: 'active',
  },
  {
    id: 'nl-nl-salary-category',
    locale: 'nl-NL',
    category: 'salary',
    slug: 'salary',
    pageType: 'category',
    primaryKeyword: 'salaris calculators nederland',
    secondaryKeywords: ['bruto netto calculator', 'loon berekenen'],
    year: null,
    contentKey: 'salaryCategory',
    status: 'active',
  },
  {
    id: 'nl-nl-bruto-netto',
    locale: 'nl-NL',
    category: 'salary',
    slug: 'salary/bruto-netto-calculator',
    pageType: 'calculator',
    calculatorType: 'nlBruttoNetto',
    primaryKeyword: 'bruto netto calculator',
    description: 'Bereken uw netto salaris na inkomstenbelasting en premies voor 2026.',
    secondaryKeywords: ['netto salaris berekenen', 'loonbelasting 2026', 'salaris calculator nederland 2026'],
    year: 2026,
    contentKey: 'nlBruttoNetto',
    equivalentPageGroup: 'nl-bruto-netto-calculator',
    status: 'active',
  },
  {
    id: 'nl-nl-salary-to-hourly',
    locale: 'nl-NL',
    category: 'salary',
    slug: 'salary/salaris-naar-uurloon',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'salaris naar uurloon calculator',
    description: 'Bereken uw equivalent uurloon op basis van uw jaarsalaris en gewerkte uren.',
    secondaryKeywords: ['uurloon berekenen', 'jaarsalaris naar uurloon', 'loon per uur berekenen'],
    year: null,
    contentKey: 'nlSalaryToHourly',
    equivalentPageGroup: 'salary-to-hourly',
    status: 'active',
  },
  {
    id: 'nl-nl-pay-frequency',
    locale: 'nl-NL',
    category: 'salary',
    slug: 'salary/salarisperiode-converter',
    pageType: 'calculator',
    calculatorType: 'payFrequencyConverter',
    primaryKeyword: 'salarisperiode converter',
    description: 'Converteer uw loon tussen wekelijks, tweewekelijks, maandelijks en jaarlijks.',
    secondaryKeywords: ['loon omrekenen', 'maandloon naar jaarloon', 'salarisconversie'],
    year: null,
    contentKey: 'nlPayFrequency',
    equivalentPageGroup: 'pay-frequency',
    status: 'active',
  },
  {
    id: 'nl-nl-salary-raise',
    locale: 'nl-NL',
    category: 'salary',
    slug: 'salary/salarisverhoging-calculator',
    pageType: 'calculator',
    calculatorType: 'salaryRaise',
    primaryKeyword: 'salarisverhoging calculator',
    description: 'Bereken uw nieuwe salaris na een procentuele of vaste loonsverhoging.',
    secondaryKeywords: ['loonsverhoging berekenen', 'salaris verhoging', 'nieuwe salaris berekenen'],
    year: null,
    contentKey: 'nlSalaryRaise',
    equivalentPageGroup: 'salary-raise',
    status: 'active',
  },
  {
    id: 'nl-nl-vakantiegeld',
    locale: 'nl-NL',
    category: 'salary',
    slug: 'salary/vakantiegeld-calculator',
    pageType: 'calculator',
    calculatorType: 'nlVakantiegeld',
    primaryKeyword: 'vakantiegeld calculator',
    description: 'Bereken uw vakantiegeld 2026 op basis van uw bruto jaarsalaris en gewerkte maanden.',
    secondaryKeywords: ['vakantiegeld berekenen', 'vakantietoeslag 2026', 'vakantiegeld pro rata'],
    year: 2026,
    contentKey: 'nlVakantiegeld',
    equivalentPageGroup: 'nl-vakantiegeld-calculator',
    status: 'active',
  },
  {
    id: 'nl-nl-minimumloon',
    locale: 'nl-NL',
    category: 'salary',
    slug: 'salary/minimumloon-calculator',
    pageType: 'calculator',
    calculatorType: 'nlMinimumloon',
    primaryKeyword: 'minimumloon calculator 2026',
    description: 'Check uw uurloon tegen het wettelijk minimumloon 2026 (€14,06/uur).',
    secondaryKeywords: ['minimumloon 2026', 'wettelijk minimumloon', 'minimumloon per uur'],
    year: 2026,
    contentKey: 'nlMinimumloon',
    equivalentPageGroup: 'nl-minimumloon-calculator',
    status: 'active',
  },
  {
    id: 'nl-nl-zzp-netto',
    locale: 'nl-NL',
    category: 'salary',
    slug: 'salary/zzp-netto-calculator',
    pageType: 'calculator',
    calculatorType: 'nlZZP',
    primaryKeyword: 'zzp netto inkomen calculator',
    description: 'Bereken uw netto inkomen als ZZP\'er 2026 na zelfstandigenaftrek, MKB-winstvrijstelling en belasting.',
    secondaryKeywords: ['zzp belasting berekenen', 'zzp netto 2026', 'zelfstandige netto inkomen', 'uurtarief zzp berekenen'],
    year: 2026,
    contentKey: 'nlZZPNetto',
    equivalentPageGroup: 'nl-zzp-netto-calculator',
    status: 'active',
  },
  {
    id: 'nl-nl-rent-affordability',
    locale: 'nl-NL',
    category: 'rent',
    slug: 'rent/huur-berekenen',
    pageType: 'calculator',
    calculatorType: 'rentAffordability',
    primaryKeyword: 'hoeveel huur kan ik betalen',
    description: 'Bereken hoeveel huur u zich kunt veroorloven op basis van uw inkomen.',
    secondaryKeywords: ['huurberekening', 'maximale huur berekenen', 'huur inkomen ratio'],
    year: null,
    contentKey: 'nlRentAffordability',
    equivalentPageGroup: 'rent-affordability',
    status: 'active',
  },
  // ── nl-NL rent category ───────────────────────────────────────────
  {
    id: 'nl-nl-rent-category',
    locale: 'nl-NL',
    category: 'rent',
    slug: 'rent',
    pageType: 'category',
    primaryKeyword: 'huurcalculators nederland',
    secondaryKeywords: ['hoeveel huur kan ik betalen', 'huurberekening'],
    year: null,
    contentKey: 'rentCategory',
    status: 'active',
  },
  // ── en-GB extra calculators ────────────────────────────────────────
  {
    id: 'en-gb-rent-category',
    locale: 'en-GB',
    category: 'rent',
    slug: 'rent',
    pageType: 'category',
    primaryKeyword: 'rent calculators uk',
    secondaryKeywords: ['rent affordability uk', 'how much rent can i afford uk'],
    year: null,
    contentKey: 'rentCategory',
    status: 'active',
  },
  {
    id: 'en-gb-pay-frequency',
    locale: 'en-GB',
    category: 'salary',
    slug: 'salary/pay-frequency-converter',
    pageType: 'calculator',
    calculatorType: 'payFrequencyConverter',
    primaryKeyword: 'pay frequency converter uk',
    description: 'Convert your UK pay between weekly, fortnightly, monthly, and annual amounts.',
    secondaryKeywords: ['convert pay periods uk', 'monthly to weekly pay uk', 'salary converter uk'],
    year: null,
    contentKey: 'gbPayFrequency',
    equivalentPageGroup: 'pay-frequency',
    status: 'active',
  },
  {
    id: 'en-gb-salary-raise',
    locale: 'en-GB',
    category: 'salary',
    slug: 'salary/salary-raise',
    pageType: 'calculator',
    calculatorType: 'salaryRaise',
    primaryKeyword: 'salary raise calculator uk',
    description: 'Calculate your new UK salary after a percentage or flat-amount pay rise.',
    secondaryKeywords: ['pay rise calculator uk', 'salary increase calculator', 'new salary after raise uk'],
    year: null,
    contentKey: 'gbSalaryRaise',
    equivalentPageGroup: 'salary-raise',
    status: 'active',
  },
  {
    id: 'en-gb-rent-affordability',
    locale: 'en-GB',
    category: 'rent',
    slug: 'rent/rent-affordability',
    pageType: 'calculator',
    calculatorType: 'rentAffordability',
    primaryKeyword: 'rent affordability calculator uk',
    description: 'Find out how much rent you can afford based on the 30% rule and your UK income.',
    secondaryKeywords: ['how much rent can i afford uk', 'rent calculator uk', '30 percent rule rent uk'],
    year: null,
    contentKey: 'gbRentAffordability',
    equivalentPageGroup: 'rent-affordability',
    status: 'active',
  },
  // ── en-IE extra calculators ────────────────────────────────────────
  {
    id: 'en-ie-rent-category',
    locale: 'en-IE',
    category: 'rent',
    slug: 'rent',
    pageType: 'category',
    primaryKeyword: 'rent calculators ireland',
    secondaryKeywords: ['rent affordability ireland', 'how much rent can i afford ireland'],
    year: null,
    contentKey: 'rentCategory',
    status: 'active',
  },
  {
    id: 'en-ie-salary-to-hourly',
    locale: 'en-IE',
    category: 'salary',
    slug: 'salary/salary-to-hourly',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'salary to hourly calculator ireland',
    description: 'Convert your annual Irish salary to an equivalent hourly rate.',
    secondaryKeywords: ['hourly rate calculator ireland', 'annual to hourly ireland'],
    year: null,
    contentKey: 'ieSalaryToHourly',
    equivalentPageGroup: 'salary-to-hourly',
    status: 'active',
  },
  {
    id: 'en-ie-pay-frequency',
    locale: 'en-IE',
    category: 'salary',
    slug: 'salary/pay-frequency-converter',
    pageType: 'calculator',
    calculatorType: 'payFrequencyConverter',
    primaryKeyword: 'pay frequency converter ireland',
    description: 'Convert your Irish pay between weekly, fortnightly, monthly, and annual amounts.',
    secondaryKeywords: ['convert pay periods ireland', 'monthly to weekly pay ireland'],
    year: null,
    contentKey: 'iePayFrequency',
    equivalentPageGroup: 'pay-frequency',
    status: 'active',
  },
  {
    id: 'en-ie-salary-raise',
    locale: 'en-IE',
    category: 'salary',
    slug: 'salary/salary-raise',
    pageType: 'calculator',
    calculatorType: 'salaryRaise',
    primaryKeyword: 'salary raise calculator ireland',
    description: 'Calculate your new Irish salary after a percentage or flat-amount pay increase.',
    secondaryKeywords: ['pay rise calculator ireland', 'salary increase ireland'],
    year: null,
    contentKey: 'ieSalaryRaise',
    equivalentPageGroup: 'salary-raise',
    status: 'active',
  },
  {
    id: 'en-ie-rent-affordability',
    locale: 'en-IE',
    category: 'rent',
    slug: 'rent/rent-affordability',
    pageType: 'calculator',
    calculatorType: 'rentAffordability',
    primaryKeyword: 'rent affordability calculator ireland',
    description: 'Find out how much rent you can afford based on your income in Ireland.',
    secondaryKeywords: ['how much rent can i afford ireland', 'rent calculator ireland'],
    year: null,
    contentKey: 'ieRentAffordability',
    equivalentPageGroup: 'rent-affordability',
    status: 'active',
  },
  // ── es-ES extra calculators ────────────────────────────────────────
  {
    id: 'es-es-salary-to-hourly',
    locale: 'es-ES',
    category: 'salary',
    slug: 'salary/calculadora-salario-hora',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'calculadora salario hora españa',
    description: 'Convierte tu salario anual bruto en un equivalente por hora según tus horas trabajadas.',
    secondaryKeywords: ['salario por hora españa', 'convertir salario anual a hora', 'sueldo por hora'],
    year: null,
    contentKey: 'esSalaryToHourly',
    equivalentPageGroup: 'salary-to-hourly',
    status: 'active',
  },
  {
    id: 'es-es-pay-frequency',
    locale: 'es-ES',
    category: 'salary',
    slug: 'salary/conversor-periodo-pago',
    pageType: 'calculator',
    calculatorType: 'payFrequencyConverter',
    primaryKeyword: 'conversor periodo de pago españa',
    description: 'Convierte tu salario entre semanal, quincenal, mensual y anual.',
    secondaryKeywords: ['convertir sueldo mensual a anual', 'calculadora periodos de pago', 'salario semanal mensual'],
    year: null,
    contentKey: 'esPayFrequency',
    equivalentPageGroup: 'pay-frequency',
    status: 'active',
  },
  // ── de-DE extra calculators ────────────────────────────────────────
  {
    id: 'de-de-rent-category',
    locale: 'de-DE',
    category: 'rent',
    slug: 'rent',
    pageType: 'category',
    primaryKeyword: 'mietrechner deutschland',
    secondaryKeywords: ['wie viel miete kann ich mir leisten', 'mietbelastungsrechner'],
    year: null,
    contentKey: 'rentCategory',
    status: 'active',
  },
  {
    id: 'de-de-rent-affordability',
    locale: 'de-DE',
    category: 'rent',
    slug: 'rent/mietbelastungsrechner',
    pageType: 'calculator',
    calculatorType: 'rentAffordability',
    primaryKeyword: 'mietbelastungsrechner',
    description: 'Ermitteln Sie Ihre maximale Miete basierend auf Ihrem Einkommen.',
    secondaryKeywords: ['wie viel miete kann ich mir leisten', 'mietrechner', 'mietbelastung berechnen'],
    year: null,
    contentKey: 'deRentAffordability',
    equivalentPageGroup: 'rent-affordability',
    status: 'active',
  },
  // ── pt-BR extra calculators ────────────────────────────────────────
  {
    id: 'pt-br-rent-category',
    locale: 'pt-BR',
    category: 'rent',
    slug: 'rent',
    pageType: 'category',
    primaryKeyword: 'calculadoras de aluguel brasil',
    secondaryKeywords: ['quanto posso pagar de aluguel', 'calculadora aluguel'],
    year: null,
    contentKey: 'rentCategory',
    status: 'active',
  },
  {
    id: 'pt-br-rent-affordability',
    locale: 'pt-BR',
    category: 'rent',
    slug: 'rent/calculadora-aluguel',
    pageType: 'calculator',
    calculatorType: 'rentAffordability',
    primaryKeyword: 'quanto posso pagar de aluguel',
    description: 'Calcule o valor máximo de aluguel com base na sua renda usando a regra dos 30%.',
    secondaryKeywords: ['calculadora de aluguel', 'quanto gastar com aluguel', 'regra dos 30 por cento aluguel'],
    year: null,
    contentKey: 'brRentAffordability',
    equivalentPageGroup: 'rent-affordability',
    status: 'active',
  },
  // ── es-MX extra calculators ────────────────────────────────────────
  {
    id: 'es-mx-salary-to-hourly',
    locale: 'es-MX',
    category: 'salary',
    slug: 'salary/calculadora-salario-hora',
    pageType: 'calculator',
    calculatorType: 'salaryToHourly',
    primaryKeyword: 'calculadora salario a hora méxico',
    description: 'Convierte tu salario anual en un equivalente por hora según tus horas laboradas.',
    secondaryKeywords: ['salario por hora mexico', 'convertir salario anual a hora mexico', 'sueldo por hora'],
    year: null,
    contentKey: 'mxSalaryToHourly',
    equivalentPageGroup: 'salary-to-hourly',
    status: 'active',
  },
  {
    id: 'es-mx-pay-frequency',
    locale: 'es-MX',
    category: 'salary',
    slug: 'salary/conversor-periodo-pago',
    pageType: 'calculator',
    calculatorType: 'payFrequencyConverter',
    primaryKeyword: 'conversor periodo de pago méxico',
    description: 'Convierte tu sueldo entre semanal, quincenal, mensual y anual conforme a la LFT.',
    secondaryKeywords: ['convertir sueldo quincenal a mensual', 'calculadora periodos pago mexico', 'sueldo quincenal'],
    year: null,
    contentKey: 'mxPayFrequency',
    equivalentPageGroup: 'pay-frequency',
    status: 'active',
  },
];

export function getActivePages(): PageDefinition[] {
  return pageRegistry.filter((p) => p.status === 'active');
}

export function getActivePagesForLocale(locale: string): PageDefinition[] {
  return getActivePages().filter((p) => p.locale === locale);
}

export function findActivePage(locale: string, slug: string): PageDefinition | undefined {
  return getActivePages().find((p) => p.locale === locale && p.slug === slug);
}

/** Pages sharing an equivalentPageGroup are true cross-locale equivalents, eligible for hreflang. */
export function findEquivalentPages(group: string): PageDefinition[] {
  return getActivePages().filter((p) => p.equivalentPageGroup === group);
}

/** Active pages that should appear in the sitemap (indexable defaults to true when unset). */
export function getIndexablePages(): PageDefinition[] {
  return getActivePages().filter((p) => p.indexable !== false);
}
